export type Lang = 'ru' | 'en';

const translations = {
  ru: {
    title: 'SLIME SURVIVORS',
    start: 'НАЧАТЬ',
    settings: 'НАСТРОЙКИ',
    language: 'ЯЗЫК',
    back: 'НАЗАД',
    levelUp: 'УРОВЕНЬ\nПОВЫШЕН!',
    gameOver: 'ИГРА\nОКОНЧЕНА',
    survived: 'Выжил',
    enemiesDefeated: 'Врагов убито',
    levelReached: 'Достигнут уровень',
    playAgain: 'ЕЩЁ РАЗ',
    mainMenu: 'МЕНЮ',
    kills: 'Убийств',
    lakeBuff: 'Бафф озера',
    levelLabel: 'Уровень',
    moveHint: 'Двигайся и выживай как можно дольше!',
    upgDmg: '+20% Урон',
    upgAtkSpd: '+20% Скорость атаки',
    upgMoveSpd: '+15% Скорость',
    upgHp: '+50 Макс. HP',
    upgProj: '+1 Снаряд',
    upgSlimeSpray: 'Разблокировать:\nСлизевой ливень',
    upgStickyWeb: 'Разблокировать:\nЛипкая паутина',
    upgShrink: '-0.5 Размер, -50 Макс. HP',
    upgSplit: '⚡ Разделение: -25% HP → мини-клон',
    pause: 'ПАУЗА',
    resume: 'ПРОДОЛЖИТЬ',
    pauseStats: 'ХАРАКТЕРИСТИКИ',
    statHP: 'Здоровье',
    statMaxHP: 'Макс. HP',
    statSpeed: 'Скорость',
    statDamage: 'Урон (x)',
    statAtkSpeed: 'Скор. атаки (x)',
    statProjectiles: 'Снаряды',
    statWeapons: 'Оружия',
    statSize: 'Размер',
    effectLakeBuff: '💧 Бафф озера',
    effectSlimeSpray: '💦 Слизевой ливень',
    effectStickyWeb: '🕸 Липкая паутина',
    weaponBolt: 'Слизевой снаряд',
    weaponSpray: 'Слизевой ливень',
    weaponWeb: 'Липкая паутина',
    difficulty: 'СЛОЖНОСТЬ',
    diffEasy: '🌿 ЛЕГКО',
    diffMedium: '⚔️ СРЕДНЕ',
    diffHard: '💀 СЛОЖНО',
    diffEasyDesc: 'Врагов в 3 раза меньше',
    diffMediumDesc: 'Врагов в 2 раза меньше',
    diffHardDesc: 'Максимальное количество врагов',
    chest: 'СУНДУК!',
    artifact: 'АРТЕФАКТ',
    artifactFound: 'Найден артефакт!',
    artMagnet: '🧲 Магнит',
    artMagnetDesc: 'Опыт тянется с 3× большего расстояния',
    artThorns: '🌵 Шипы',
    artThornsDesc: 'Ближние враги получают 5 урона/сек',
    artRegen: '💚 Регенерация',
    artRegenDesc: 'Восстановление 2 HP/сек',
    artBerserker: '🔥 Берсерк',
    artBerserkerDesc: '+40% урона при HP < 50%',
    artIronSkin: '🛡 Железная кожа',
    artIronSkinDesc: '-20% получаемого урона',
    artSwift: '👟 Быстрые ноги',
    artSwiftDesc: '+25% скорость навсегда',
    selectHero: 'ВЫБОР ГЕРОЯ',
    heroBlue: '🔵 Синий слизень',
    heroBlueDesc: 'Сбалансированный герой, 100 HP',
    heroGreen: '🟢 Зелёный слизень',
    heroGreenDesc: '+30% урон, −30% здоровье\nЗелёные снаряды',
    heroPurple: '🟣 Фиолетовый слизень',
    heroPurpleDesc: '+50% здоровье, −30% скорость\n−20% скор. атаки, фиолетовые снаряды',
    musicVol: 'МУЗЫКА',
    volDown: '🔉 Тише',
    volUp: '🔊 Громче',
    miniClone: 'Мини-клон',
    bossWarning: '☠️ ЯВИЛСЯ БЕССМЕРТНЫЙ УЖАС!',
    youWin: 'ТЫ\nВЫЖИЛ!',
    youWinSub: '30 минут выдержано — победа!',
  },
  en: {
    title: 'SLIME SURVIVORS',
    start: 'START',
    settings: 'SETTINGS',
    language: 'LANGUAGE',
    back: 'BACK',
    levelUp: 'LEVEL UP!',
    gameOver: 'GAME\nOVER',
    survived: 'Survived',
    enemiesDefeated: 'Enemies Defeated',
    levelReached: 'Level Reached',
    playAgain: 'PLAY AGAIN',
    mainMenu: 'MAIN MENU',
    kills: 'Kills',
    lakeBuff: 'Lake Buff',
    levelLabel: 'Level',
    moveHint: 'Move and survive as long as possible!',
    upgDmg: '+20% Damage',
    upgAtkSpd: '+20% Attack Speed',
    upgMoveSpd: '+15% Move Speed',
    upgHp: '+50 Max HP',
    upgProj: '+1 Projectile',
    upgSlimeSpray: 'Unlock:\nSlime Spray',
    upgStickyWeb: 'Unlock:\nSticky Web',
    upgShrink: '-0.5 Size, -50 Max HP',
    upgSplit: '⚡ Split: −25% HP → mini clone',
    pause: 'PAUSE',
    resume: 'RESUME',
    pauseStats: 'STATS',
    statHP: 'Health',
    statMaxHP: 'Max HP',
    statSpeed: 'Speed',
    statDamage: 'Damage (x)',
    statAtkSpeed: 'Atk Speed (x)',
    statProjectiles: 'Projectiles',
    statWeapons: 'Weapons',
    statSize: 'Size',
    effectLakeBuff: '💧 Lake Buff',
    effectSlimeSpray: '💦 Slime Spray',
    effectStickyWeb: '🕸 Sticky Web',
    weaponBolt: 'Slime Bolt',
    weaponSpray: 'Slime Spray',
    weaponWeb: 'Sticky Web',
    difficulty: 'DIFFICULTY',
    diffEasy: '🌿 EASY',
    diffMedium: '⚔️ MEDIUM',
    diffHard: '💀 HARD',
    diffEasyDesc: '3× fewer enemies',
    diffMediumDesc: '2× fewer enemies',
    diffHardDesc: 'Maximum enemy count',
    chest: 'CHEST!',
    artifact: 'ARTIFACT',
    artifactFound: 'Artifact found!',
    artMagnet: '🧲 Magnet',
    artMagnetDesc: 'XP orbs attract from 3× further',
    artThorns: '🌵 Thorns',
    artThornsDesc: 'Nearby enemies take 5 damage/sec',
    artRegen: '💚 Regeneration',
    artRegenDesc: 'Restore 2 HP/sec',
    artBerserker: '🔥 Berserker',
    artBerserkerDesc: '+40% damage when HP < 50%',
    artIronSkin: '🛡 Iron Skin',
    artIronSkinDesc: '-20% incoming damage',
    artSwift: '👟 Swift Boots',
    artSwiftDesc: '+25% speed permanently',
    selectHero: 'CHOOSE HERO',
    heroBlue: '🔵 Blue Slime',
    heroBlueDesc: 'Balanced hero, 100 HP',
    heroGreen: '🟢 Green Slime',
    heroGreenDesc: '+30% damage, −30% HP\nGreen projectiles',
    heroPurple: '🟣 Purple Slime',
    heroPurpleDesc: '+50% HP, −30% speed\n−20% attack speed, purple projectiles',
    musicVol: 'MUSIC',
    volDown: '🔉 Volume Down',
    volUp: '🔊 Volume Up',
    miniClone: 'Mini Clone',
    bossWarning: '☠️ THE IMMORTAL HAS ARRIVED!',
    youWin: 'YOU\nSURVIVED!',
    youWinSub: '30 minutes survived — victory!',
  },
} as const;

let _lang: Lang = 'ru';

export function setLang(l: Lang): void { _lang = l; }
export function getLang(): Lang { return _lang; }
export function t(key: keyof typeof translations.en): string {
  return translations[_lang][key];
}
