export type Lang = 'ru' | 'en';

const translations = {
  ru: {
    title: 'SLIME SURVIVORS',
    start: 'НАЧАТЬ',
    settings: 'НАСТРОЙКИ',
    info: 'подробнее',
    language: 'ЯЗЫК',
    back: 'НАЗАД',
    levelUp: 'УРОВЕНЬ\nПОВЫШЕН!',
    gameOver: 'ИГРА\nОКОНЧЕНА',
    survived: 'Выжил',
    enemiesDefeated: 'Врагов убито',
    levelReached: 'Достигнут уровень',
    playAgain: 'ЕЩЁ РАЗ',
    mainMenu: 'МЕНЮ',
    kills: 'Убийств',
    lakeBuff: 'Бафф озера',
    levelLabel: 'Уровень',
    moveHint: 'Двигайся и выживай как можно дольше!',
    upgDmg: '+20% Урон',
    upgAtkSpd: '+20% Скорость атаки',
    upgMoveSpd: '+15% Скорость',
    upgHp: '+50 Макс. HP',
    upgProj: '+1 Снаряд',
    upgSlimeSpray: 'Разблокировать:\nСлизевой ливень',
    upgStickyWeb: 'Разблокировать:\nЛипкая паутина',
    upgShrink: '-0.5 Размер, -50 Макс. HP',
    upgSplit: '⚡ Разделение: -25% HP → мини-клон',
    upgDmgDesc: 'Увеличивает урон всех атак на 20%.',
    upgAtkSpdDesc: 'Уменьшает время между атаками на 20%.',
    upgMoveSpdDesc: 'Увеличивает скорость передвижения на 15%.',
    upgHpDesc: 'Добавляет 50 к максимальному HP и восстанавливает это количество.',
    upgProjDesc: 'Добавляет один дополнительный снаряд к атаке.',
    upgSlimeSprayDesc: 'Открывает круговой залп из слизевых снарядов.',
    upgStickyWebDesc: 'Открывает ауру паутины, замедляющую ближайших врагов.',
    upgShrinkDesc: 'Уменьшает размер и максимальное HP на 50.',
    upgSplitDesc: 'Тратит 25% текущего HP и создаёт мини-клона, который атакует рядом.',
    pause: 'ПАУЗА',
    resume: 'ПРОДОЛЖИТЬ',
    pauseStats: 'ХАРАКТЕРИСТИКИ',
    statHP: 'Здоровье',
    statMaxHP: 'Макс. HP',
    statSpeed: 'Скорость',
    statDamage: 'Урон (x)',
    statAtkSpeed: 'Скор. атаки (x)',
    statProjectiles: 'Снаряды',
    statWeapons: 'Оружия',
    statSize: 'Размер',
    effectLakeBuff: '💧 Бафф озера',
    effectSlimeSpray: '💦 Слизевой ливень',
    effectStickyWeb: '🕸 Липкая паутина',
    weaponBolt: 'Слизевой снаряд',
    weaponSpray: 'Слизевой ливень',
    weaponWeb: 'Липкая паутина',
    difficulty: 'СЛОЖНОСТЬ',
    diffEasy: '🌿 ЛЕГКО',
    diffMedium: '⚔️ СРЕДНЕ',
    diffHard: '💀 СЛОЖНО',
    diffEasyDesc: 'Малое количество врагов',
    diffMediumDesc: 'В 2 раза больше врагов',
    diffHardDesc: 'В 3 раза больше врагов',
    chest: 'СУНДУК!',
    artifact: 'АРТЕФАКТ',
    artifactFound: 'Найден артефакт!',
    artMagnet: '🧲 Магнит',
    artMagnetDesc: 'Опыт тянется с 3× большего расстояния',
    artThorns: '🌵 Шипы',
    artThornsDesc: 'Ближние враги получают 5 урона/сек',
    artRegen: '💚 Регенерация',
    artRegenDesc: 'Восстановление 2 HP/сек',
    artBerserker: '🔥 Берсерк',
    artBerserkerDesc: '+40% урона при HP < 50%',
    artIronSkin: '🛡 Железная кожа',
    artIronSkinDesc: '-20% получаемого урона',
    artSwift: '👟 Быстрые ноги',
    artSwiftDesc: '+25% скорость навсегда',
    selectHero: 'ВЫБОР ГЕРОЯ',
    heroBlue: '🔵 Синий слизень',
    heroBlueDesc: 'HP: 100\nУрон: 25 за снаряд\nСбалансированный герой',
    heroGreen: '🟢 Зелёный слизень',
    heroGreenDesc: 'HP: 70\nУрон: 32.5 за снаряд (+30%)\nЗелёные снаряды',
    heroPurple: '🟣 Фиолетовый слизень',
    heroPurpleDesc: 'HP: 150\nУрон: 25 за снаряд\n−30% скорость, −20% скорость атаки',
    musicVol: 'МУЗЫКА',
    volDown: '🔉 Тише',
    volUp: '🔊 Громче',
    miniClone: 'Мини-клон',
    bossWarning: '☠️ ЯВИЛСЯ БЕССМЕРТНЫЙ УЖАС!',
    youWin: 'ТЫ\nВЫЖИЛ!',
    youWinSub: '30 минут выдержано — победа!',
  },
  en: {
    title: 'SLIME SURVIVORS',
    start: 'START',
    settings: 'SETTINGS',
    info: 'more info',
    language: 'LANGUAGE',
    back: 'BACK',
    levelUp: 'LEVEL UP!',
    gameOver: 'GAME\nOVER',
    survived: 'Survived',
    enemiesDefeated: 'Enemies Defeated',
    levelReached: 'Level Reached',
    playAgain: 'PLAY AGAIN',
    mainMenu: 'MAIN MENU',
    kills: 'Kills',
    lakeBuff: 'Lake Buff',
    levelLabel: 'Level',
    moveHint: 'Move and survive as long as possible!',
    upgDmg: '+20% Damage',
    upgAtkSpd: '+20% Attack Speed',
    upgMoveSpd: '+15% Move Speed',
    upgHp: '+50 Max HP',
    upgProj: '+1 Projectile',
    upgSlimeSpray: 'Unlock:\nSlime Spray',
    upgStickyWeb: 'Unlock:\nSticky Web',
    upgShrink: '-0.5 Size, -50 Max HP',
    upgSplit: '⚡ Split: −25% HP → mini clone',
    upgDmgDesc: 'Increases damage from all attacks by 20%.',
    upgAtkSpdDesc: 'Reduces the time between attacks by 20%.',
    upgMoveSpdDesc: 'Increases movement speed by 15%.',
    upgHpDesc: 'Adds 50 max HP and restores the same amount.',
    upgProjDesc: 'Adds one extra projectile to each attack.',
    upgSlimeSprayDesc: 'Unlocks a circular burst of slime projectiles.',
    upgStickyWebDesc: 'Unlocks a web aura that slows nearby enemies.',
    upgShrinkDesc: 'Makes the slime smaller and removes 50 max HP.',
    upgSplitDesc: 'Spends 25% current HP and creates a mini clone that attacks nearby.',
    pause: 'PAUSE',
    resume: 'RESUME',
    pauseStats: 'STATS',
    statHP: 'Health',
    statMaxHP: 'Max HP',
    statSpeed: 'Speed',
    statDamage: 'Damage (x)',
    statAtkSpeed: 'Atk Speed (x)',
    statProjectiles: 'Projectiles',
    statWeapons: 'Weapons',
    statSize: 'Size',
    effectLakeBuff: '💧 Lake Buff',
    effectSlimeSpray: '💦 Slime Spray',
    effectStickyWeb: '🕸 Sticky Web',
    weaponBolt: 'Slime Bolt',
    weaponSpray: 'Slime Spray',
    weaponWeb: 'Sticky Web',
    difficulty: 'DIFFICULTY',
    diffEasy: '🌿 EASY',
    diffMedium: '⚔️ MEDIUM',
    diffHard: '💀 HARD',
    diffEasyDesc: 'Few enemies',
    diffMediumDesc: '2× more enemies',
    diffHardDesc: '3× more enemies',
    chest: 'CHEST!',
    artifact: 'ARTIFACT',
    artifactFound: 'Artifact found!',
    artMagnet: '🧲 Magnet',
    artMagnetDesc: 'XP orbs attract from 3× further',
    artThorns: '🌵 Thorns',
    artThornsDesc: 'Nearby enemies take 5 damage/sec',
    artRegen: '💚 Regeneration',
    artRegenDesc: 'Restore 2 HP/sec',
    artBerserker: '🔥 Berserker',
    artBerserkerDesc: '+40% damage when HP < 50%',
    artIronSkin: '🛡 Iron Skin',
    artIronSkinDesc: '-20% incoming damage',
    artSwift: '👟 Swift Boots',
    artSwiftDesc: '+25% speed permanently',
    selectHero: 'CHOOSE HERO',
    heroBlue: '🔵 Blue Slime',
    heroBlueDesc: 'HP: 100\nDamage: 25 per projectile\nBalanced hero',
    heroGreen: '🟢 Green Slime',
    heroGreenDesc: 'HP: 70\nDamage: 32.5 per projectile (+30%)\nGreen projectiles',
    heroPurple: '🟣 Purple Slime',
    heroPurpleDesc: 'HP: 150\nDamage: 25 per projectile\n−30% speed, −20% attack speed',
    musicVol: 'MUSIC',
    volDown: '🔉 Volume Down',
    volUp: '🔊 Volume Up',
    miniClone: 'Mini Clone',
    bossWarning: '☠️ THE IMMORTAL HAS ARRIVED!',
    youWin: 'YOU\nSURVIVED!',
    youWinSub: '30 minutes survived — victory!',
  },
} as const;

let _lang: Lang = 'ru';

export function setLang(l: Lang): void { _lang = l; }
export function getLang(): Lang { return _lang; }
export function t(key: keyof typeof translations.en): string {
  return translations[_lang][key];
}
